dubbo:
  application:
    name: shop_user_service
  registry:
    address: zookeeper://192.168.87.128:2181
  protocol:
    port: -1
    name: dubbo
spring:
  datasource:
    url: jdbc:mysql:///shop1901?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #配置数据库连接池为阿里的druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
      min-idle: 10
      min-evictable-idle-time-millis: 60000